name: Publish Docker image

on:
  push:
    branches:
      - development

jobs:

  build_and_publish:
    environment: development
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folders_list: ["image_api", "image_processing"]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build and publish docker images
      run: |
        echo ${{ secrets.CI_CD_SA_KEY }} | base64 -d > keyfile.json
        cat keyfile.json | docker login -u _json_key --password-stdin https://us.gcr.io
        cd ${{ matrix.folders_list }}
        export VERSION=$(npm run version --silent)
        export NAME=$(npm run version --silent)
        docker build -t $NAME .
        docker tag  $NAME us.gcr.io/dev-ibe-lbme-img-proc/$NAME:$VERSION
        docker push us.gcr.io/dev-ibe-lbme-img-proc/$NAME:$VERSION
